{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.14.jar",
          "url": "spring-webmvc-6.1.14.jar",
          "size": 1048416,
          "sha512": "97c92b18929969d34f74d70f6ae95ce18de66f8fe06a43baa03d923885dafe404d8bab870c96e1a768d6685b2d875b955cbbb9a57ed293ecbf2f7bd9759a5e59",
          "sha256": "9f096f7530ed385348d269dd9ad642dff47f50cbc758f17d69484952cdd0cbc0",
          "sha1": "804478303aac6f91ea566efd4fef3dc06380528a",
          "md5": "8a0a9223944f008cbc885f4dc42bbdb7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.14"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.14"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.14.jar",
          "url": "spring-webmvc-6.1.14.jar",
          "size": 1048416,
          "sha512": "97c92b18929969d34f74d70f6ae95ce18de66f8fe06a43baa03d923885dafe404d8bab870c96e1a768d6685b2d875b955cbbb9a57ed293ecbf2f7bd9759a5e59",
          "sha256": "9f096f7530ed385348d269dd9ad642dff47f50cbc758f17d69484952cdd0cbc0",
          "sha1": "804478303aac6f91ea566efd4fef3dc06380528a",
          "md5": "8a0a9223944f008cbc885f4dc42bbdb7"
        }
      ]
    }
  ]
}
