{
  "formatVersion": "1.1",
  "component": {
    "group": "org.checkerframework",
    "module": "checker-qual",
    "version": "3.37.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "checker-qual-3.37.0.jar",
          "url": "checker-qual-3.37.0.jar",
          "size": 224460,
          "sha512": "98f92a4d14b77f2946de34bc64bc0068505ba8893a734e52f6458e3061fc7471bd5a60c073c938302b7b78d51205929134207abc24f0edadd3db1e1f57755de5",
          "sha256": "e4ce1376cc2735e1dde220b62ad0913f51297704daad155a33f386bc5db0d9f7",
          "sha1": "ba74746d38026581c12166e164bb3c15e90cc4ea",
          "md5": "1ff1eed173ff9d6f208d0a5be8f5623d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.37.0.jar",
          "url": "checker-qual-3.37.0.jar",
          "size": 224460,
          "sha512": "98f92a4d14b77f2946de34bc64bc0068505ba8893a734e52f6458e3061fc7471bd5a60c073c938302b7b78d51205929134207abc24f0edadd3db1e1f57755de5",
          "sha256": "e4ce1376cc2735e1dde220b62ad0913f51297704daad155a33f386bc5db0d9f7",
          "sha1": "ba74746d38026581c12166e164bb3c15e90cc4ea",
          "md5": "1ff1eed173ff9d6f208d0a5be8f5623d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.37.0-javadoc.jar",
          "url": "checker-qual-3.37.0-javadoc.jar",
          "size": 990349,
          "sha512": "fbe5855d2a69be10e69b555e7fa47b38dbc6e0431a38b5299c295026f03e52372028f27188eca5a0014def7da17a886c956a6a399500a19c0f18f413289d5e06",
          "sha256": "228511bd7df970b08f90628a8c4355f8bb5f00162d4b63b5d8f2d03fe4f054d4",
          "sha1": "7d22f9f289e8844fae23e136087e89e18ee49749",
          "md5": "78dd30464a948374efb165964f6786e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "checker-qual-3.37.0-sources.jar",
          "url": "checker-qual-3.37.0-sources.jar",
          "size": 255444,
          "sha512": "906a23b8a8f58dbac0134b9d086d430000858a2c2946b74f5078412a2587a790d5ce657eface11f136cea6714d5825ac2f4b6992009706dddd3885fa81e1c66f",
          "sha256": "2ca31c7e959ad82fe270b2baac11a59c570f8778191233c54927e94adab7b640",
          "sha1": "9990309889a76e4c6556c18140ce8559b854bae3",
          "md5": "439780a10f3fc7d3938340de65048079"
        }
      ]
    }
  ]
}
